server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/medibook_auth_db
    username: root
    password: surbhi123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: surbhisahu3075@gmail.com
    password: "cmby qiuz tgwo qskp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  upload-dir: uploads