server:
  port: 8088

spring:
  application:
    name: record-service
  datasource:
    url: jdbc:mysql://localhost:3306/medibook_record?createDatabaseIfNotExist=true
    username: root
    password: surbhi123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/